const capabilities = [
  ["Firm worklist", "See active work, responsibility, and status in one focused view."],
  ["Client and matter records", "Keep the essential parties and matter lifecycle organised."],
  ["Tasks and deadlines", "Record what must happen, who owns it, and when it is due."],
  ["Recorded decisions", "Preserve actor-attributed activity and deliberate matter transitions."],
];

const boundaries = ["No automated conflict checking", "No Ethical Walls", "No automated reminders or notifications", "No document or attachment storage"];

export default function Home() {
  return (
    <main>
      <header className="nav-shell">
        <a className="brand" href="#top" aria-label="OneLegalPro home"><span className="brand-mark">OL</span><span>OneLegalPro</span></a>
        <nav aria-label="Main navigation"><a href="#matter-desk">Matter Desk</a><a href="#pilot">Pilot</a><a href="#boundaries">Boundaries</a><a className="nav-cta" href="#contact">Request information</a></nav>
      </header>
      <section className="hero" id="top">
        <div className="hero-copy"><p className="eyebrow">Built for legal work in Thailand</p><h1>A calmer way to run the matters that matter.</h1><p className="lede">OneLegalPro Matter Desk is a focused workspace for law firms to organise clients, matters, responsibilities, tasks, and deadlines.</p><div className="hero-actions"><a className="button primary" href="#contact">Request pilot information</a><a className="button secondary" href="#matter-desk">Explore the Matter Desk</a></div><p className="availability">Founding-firm pilot · Availability by invitation</p></div>
        <div className="desk-preview" aria-label="Illustrative Matter Desk preview"><div className="preview-topline"><span>Firm worklist</span><span className="preview-pill">Illustrative preview</span></div><div className="preview-metric"><strong>12</strong><span>active matters</span></div><div className="matter-row"><span className="matter-code">MAT-026</span><span>Commercial advisory</span><span className="status">Active</span></div><div className="matter-row"><span className="matter-code">MAT-025</span><span>Corporate restructuring</span><span className="status muted">Opened</span></div><div className="preview-note">Clear ownership. Visible deadlines. Recorded decisions.</div></div>
      </section>
      <section className="statement" id="matter-desk"><p className="section-number">01 / The Matter Desk</p><div><h2>Less operational noise.<br/>More deliberate legal work.</h2><p>OneLegalPro begins with the everyday centre of a law firm: knowing which matters are open, who is responsible, what happens next, and which deadlines need attention.</p></div></section>
      <section className="capability-grid" aria-label="Matter Desk capabilities">{capabilities.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</section>
      <section className="pilot" id="pilot"><div><p className="eyebrow light">Founding-firm pilot</p><h2>Shape a practical desk with us.</h2></div><div className="pilot-copy"><p>The first release is a limited pilot for selected Thai law firms. Participating firms work directly with the operator, provide structured feedback, and receive guided onboarding.</p><p>Access is not self-service. Availability, pilot terms, fit, and timing are confirmed individually.</p><a className="text-link" href="#contact">Start a conversation <span>→</span></a></div></section>
      <section className="boundaries" id="boundaries"><div><p className="section-number">02 / Clear boundaries</p><h2>We say plainly what the pilot does not do.</h2><p>These controls and capabilities are absent from the founding-firm pilot. They are not approximated, simulated, or presented under another name.</p></div><ul>{boundaries.map(item => <li key={item}><span>Not included</span>{item}</li>)}</ul><p className="boundary-note">Manual conflict attestation records a human determination. OneLegalPro does not search for, detect, screen for, or clear conflicts.</p></section>
      <section className="contact" id="contact"><div><p className="eyebrow">Request pilot information</p><h2>Tell us about your firm.</h2><p>To avoid collecting confidential or privileged information through this public website, please keep your first message to basic firm and contact details. Do not describe a client or legal matter.</p></div><form action="mailto:info@onelegalpro.com" method="post" encType="text/plain"><label>Full name<input name="name" autoComplete="name" required /></label><label>Work email<input name="email" type="email" autoComplete="email" required /></label><label>Firm name<input name="firm" autoComplete="organization" required /></label><label>Country or jurisdiction<input name="country" autoComplete="country-name" defaultValue="Thailand" /></label><label className="full">What would you like to know?<textarea name="message" rows={4} placeholder="Please do not include client names, matter details, or confidential information." /></label><label className="consent full"><input name="consent" type="checkbox" required /><span>I have read the <a href="/privacy">Privacy Notice</a> and agree that Jand Corp Company Limited may use these details to respond to this inquiry.</span></label><button className="button primary" type="submit">Prepare email inquiry</button><p className="form-note">Submitting opens your email application. This website does not store the form contents.</p></form></section>
      <footer><div className="brand"><span className="brand-mark">OL</span><span>OneLegalPro</span></div><div><strong>Operated by Jand Corp Company Limited</strong><p>227 Soi Pattanakarn 30, Suan Luang, Bangkok 10250, Thailand</p><a href="mailto:info@onelegalpro.com">info@onelegalpro.com</a></div><div className="footer-links"><a href="/privacy">Privacy Notice</a><a href="/terms">Website Terms</a><span>© 2026 Jand Corp Company Limited</span></div></footer>
    </main>
  );
}
