import Link from "next/link";

export const metadata = { title: "Privacy Notice — OneLegalPro", description: "Privacy information for visitors and founding-firm inquiries.", openGraph: { title: "Privacy Notice — OneLegalPro", description: "Privacy information for visitors and founding-firm inquiries.", images: [] }, twitter: { title: "Privacy Notice — OneLegalPro", description: "Privacy information for visitors and founding-firm inquiries.", images: [] } };
export default function Privacy() { return <main className="legal-page"><Link className="back-link" href="/">← OneLegalPro</Link><p className="eyebrow">Draft for owner legal review</p><h1>Privacy Notice</h1><p className="legal-date">Proposed effective date: 15 September 2026</p>
<section><h2>1. Who we are</h2><p>Jand Corp Company Limited operates OneLegalPro. Our registered address is 227 Soi Pattanakarn 30, Suan Luang, Bangkok 10250, Thailand. Privacy inquiries may be sent to <a href="mailto:info@onelegalpro.com">info@onelegalpro.com</a>.</p></section>
<section><h2>2. Scope</h2><p>This notice covers the public OneLegalPro website and initial inquiries about the founding-firm pilot. It does not yet govern use of the Matter Desk service; the pilot agreement and service privacy terms will govern that processing before any firm receives access.</p></section>
<section><h2>3. Information we receive</h2><p>If you contact us, we may receive your name, work email, firm name, country or jurisdiction, message, and the ordinary technical delivery information created by your email provider. Please do not send client names, matter details, privileged material, identification documents, payment information, or other sensitive information through the public inquiry form.</p></section>
<section><h2>4. Why we use it</h2><p>We use inquiry information to respond, assess pilot fit, arrange discussions, keep a record of the request, protect the website from abuse, and comply with applicable legal obligations. The final legal basis and consent language must be confirmed in the owner’s recorded Thai-qualified legal review before publication.</p></section>
<section><h2>5. How the inquiry form works</h2><p>The launch version prepares an email in your own email application. The website does not persist the form contents. Your email provider and ours process the resulting message under their own terms and privacy practices.</p></section>
<section><h2>6. Sharing and international processing</h2><p>Website hosting, security, email, and infrastructure providers may process limited technical or message data for us. The final provider list, processing locations, safeguards, and cross-border-transfer analysis must be completed and approved before publication.</p></section>
<section><h2>7. Retention</h2><p>Inquiry information is retained only as long as reasonably necessary to respond, administer the pilot relationship, meet legal obligations, and resolve disputes. A precise retention period will be adopted in the final reviewed notice; no period is asserted by this draft.</p></section>
<section><h2>8. Your rights</h2><p>Subject to applicable law, you may have rights to request access, correction, deletion, restriction, objection, withdrawal of consent, or data portability, and to complain to the competent authority. Contact us at the address above. We may need to verify your identity before responding.</p></section>
<section><h2>9. Security and limitations</h2><p>We apply proportionate safeguards but no internet transmission is risk-free. This notice makes no certification, compliance, or absolute-security claim.</p></section>
<section><h2>10. Changes</h2><p>We may update this notice. The published version will show its effective date and will not silently rewrite a contractual service commitment.</p></section></main>; }
