import Link from "next/link";

export const metadata = { title: "Privacy Notice — OneLegalPro", description: "Privacy information for visitors and founding-firm inquiries.", openGraph: { title: "Privacy Notice — OneLegalPro", description: "Privacy information for visitors and founding-firm inquiries.", images: [] }, twitter: { title: "Privacy Notice — OneLegalPro", description: "Privacy information for visitors and founding-firm inquiries.", images: [] } };
export default function Privacy() { return <main className="legal-page"><Link className="back-link" href="/">← OneLegalPro</Link><p className="eyebrow">Public website</p><h1>Privacy Notice</h1><p className="legal-date">Effective date: 15 September 2026</p>
<section><h2>1. Who we are</h2><p>Jand Corp Company Limited operates OneLegalPro. Our registered address is 227 Soi Pattanakarn 30, Suan Luang, Bangkok 10250, Thailand. Privacy inquiries may be sent to <a href="mailto:info@onelegalpro.com">info@onelegalpro.com</a>.</p></section>
<section><h2>2. Scope</h2><p>This notice covers the public OneLegalPro website and initial inquiries about the founding-firm pilot. It does not yet govern use of the Matter Desk service; the pilot agreement and service privacy terms will govern that processing before any firm receives access.</p></section>
<section><h2>3. Information we receive</h2><p>If you contact us, we may receive your name, work email, firm name, country or jurisdiction, message, and the ordinary technical delivery information created by your email provider. Please do not send client names, matter details, privileged material, identification documents, payment information, or other sensitive information through the public inquiry form.</p></section>
<section><h2>4. Why we use it</h2><p>We use inquiry information to respond, assess pilot fit, arrange discussions, keep a record of the request, protect the website from abuse, and comply with applicable legal obligations. Depending on the purpose, we process this information to take steps you request before entering an agreement, for our legitimate interests in operating and protecting the inquiry process, or to comply with a legal obligation. The inquiry form does not enrol you in marketing or a mailing list.</p></section>
<section><h2>5. How the inquiry form works</h2><p>The launch version prepares an email in your own email application. The website does not persist the form contents. Your email provider and ours process the resulting message under their own terms and privacy practices.</p></section>
<section><h2>6. Hosting and security cookie</h2><p>The website does not set application, advertising, analytics, or preference cookies. Its Cloudflare-compatible hosting boundary may set the strictly necessary <code>__cf_bm</code> cookie to distinguish automated traffic and protect the site. Cloudflare states that this site-specific cookie contains encrypted bot-management information, does not identify a user in the OneLegalPro application, and expires after 30 minutes of continuous inactivity. It is not used by OneLegalPro for advertising, analytics, preferences, or cross-site tracking.</p></section>
<section><h2>7. Sharing and international processing</h2><p>OpenAI Sites and its Cloudflare-compatible infrastructure may process limited technical data to host and protect this website. Our email provider processes a message only after you send it from your own email application. These providers may process information outside Thailand under contractual or other approved cross-border safeguards. We do not sell inquiry information.</p></section>
<section><h2>8. Retention</h2><p>We ordinarily retain an inquiry record for 24 months after the last substantive contact. We may retain it longer where necessary for an agreement, a dispute, or a legal obligation, and then only for the applicable purpose and period.</p></section>
<section><h2>9. Your rights</h2><p>Subject to applicable law, you may have rights to request access, correction, deletion, restriction, objection, withdrawal of consent, or data portability, and to complain to the competent authority. Contact us at the address above. We may need to verify your identity before responding.</p></section>
<section><h2>10. Security and limitations</h2><p>We apply proportionate safeguards but no internet transmission is risk-free. This notice makes no certification, compliance, or absolute-security claim.</p></section>
<section><h2>11. Changes</h2><p>We may update this notice. The published version will show its effective date and will not silently rewrite a contractual service commitment.</p></section></main>; }
