import Link from "next/link";

export const metadata = { title: "Website Terms — OneLegalPro", description: "Terms governing use of the public OneLegalPro website.", openGraph: { title: "Website Terms — OneLegalPro", description: "Terms governing use of the public OneLegalPro website.", images: [] }, twitter: { title: "Website Terms — OneLegalPro", description: "Terms governing use of the public OneLegalPro website.", images: [] } };
export default function Terms() { return <main className="legal-page"><Link className="back-link" href="/">← OneLegalPro</Link><p className="eyebrow">Draft for owner legal review</p><h1>Website Terms</h1><p className="legal-date">Proposed effective date: 15 September 2026</p>
<section><h2>1. Operator</h2><p>This website is operated by Jand Corp Company Limited, 227 Soi Pattanakarn 30, Suan Luang, Bangkok 10250, Thailand. Contact: <a href="mailto:info@onelegalpro.com">info@onelegalpro.com</a>.</p></section>
<section><h2>2. Website purpose</h2><p>The website provides general information about OneLegalPro and a proposed founding-firm pilot. It is not the Matter Desk service, does not provide an account, and does not guarantee acceptance into or availability of the pilot.</p></section>
<section><h2>3. No legal advice or lawyer-client relationship</h2><p>Website content is general product information, not legal advice. Using the website or contacting Jand Corp Company Limited does not create a lawyer-client, attorney-client, fiduciary, or other professional relationship.</p></section>
<section><h2>4. Pilot status and capability boundaries</h2><p>The founding-firm pilot is limited and available by invitation. It does not include Ethical Walls, automated conflict checking, automated reminders or notifications, or document and attachment storage. A manual conflict attestation records a human decision; the system does not search for, detect, screen for, or clear conflicts.</p></section>
<section><h2>5. Illustrations and forward-looking information</h2><p>Interface previews are illustrative and may change. Descriptions of planned work are not commitments that a feature will be delivered by a particular date. No availability, uptime, certification, compliance, or production-readiness guarantee is made.</p></section>
<section><h2>6. Acceptable use</h2><p>Do not misuse the website, interfere with its operation, attempt unauthorized access, submit unlawful content, or send confidential client or matter information through the public inquiry form.</p></section>
<section><h2>7. Intellectual property</h2><p>Unless stated otherwise, the website content and OneLegalPro presentation are owned by or licensed to Jand Corp Company Limited. These terms do not grant a licence except the limited right to view and use the website for its intended informational purpose.</p></section>
<section><h2>8. Third-party services</h2><p>The website may depend on hosting, security, and email services supplied by third parties. References or links do not constitute an endorsement, and third-party services may be governed by their own terms.</p></section>
<section><h2>9. Disclaimers and liability</h2><p>The website is provided on an “as available” informational basis. Any exclusions or limitations of liability in the final terms must be reviewed for validity and fairness under applicable Thai law before publication.</p></section>
<section><h2>10. Governing law and disputes</h2><p>The governing-law, jurisdiction, notice, language-precedence, and dispute provisions are intentionally left for the owner’s Thai-qualified legal determination before publication.</p></section></main>; }
